name: UltraLucky
version: '${version}'
main: dev.rgbmc.ultralucky.UltraLucky
api-version: 1.13
load: POSTWORLD
authors: [ FlyProject ]
description: The Next-Generation Open Source Lucky System Solution
softdepend:
  - PlaceholderAPI
  - FlyBuff
  - Zaphkiel
  - MagicGem
  - Vault
  - PlayerPoints
  - NBTAPI
  - MythicMobs
commands:
  ultralucky:
    aliases:
      - ulucky
      - uluck
      - lucky
    permission: ultralucky.use

permissions:
  ultralucky.use:
    default: true
  ultralucky.admin:
    default: op
