name: Build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking Environment
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          echo "Compile_Date=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - name: checkout repository
        uses: actions/checkout@v2
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Build
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: ./gradlew shadowJar publish
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
      - name: Upload Build to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/*
          file_glob: true
          tag: ${{ github.ref }}
          release_name: "UltraLucky_Dev-${{ env.Compile_Date }}"
          overwrite: true
          prerelease: false
          body: |
            UltraLucky 构建
            构建时间: ${{ env.Compile_Date }}
